### ISSUE TITLE
Too much box

### ISSUE THREAD

**Issue by salimamoukou** [penny4860/YOLO-detector#17]
I trained the model but it does not detect the numbers. There is too much box.
Please need help....

**Comment by TharakaMadhusanka** [comment]
same ! you found the issue ?
![1](https://user-images.githubusercontent.com/7240672/41806194-f9f861b0-76d6-11e8-9fc6-3174732924ce.png)
![2](https://user-images.githubusercontent.com/7240672/41806195-fa2a461c-76d6-11e8-9c2c-fd784c403b0b.png)

**Comment by salimamoukou** [comment]
Yes, the same.

**Comment by penny4860** [comment]
Is this the result of following [2-training-from-scratch](https://github.com/penny4860/Yolo-digit-detector#2-training-from-scratch)?

**Comment by salimamoukou** [comment]
Yes. I also try other training and have the same issue.

**Comment by TharakaMadhusanka** [comment]
I am just confusing, @Penny, didn't u get this kinda out put when u trial out the application ? because use the same weights same models nah

**Comment by salimamoukou** [comment]
@penny4860  ?

**Comment by penny4860** [comment]
@slimamk @TharakaMadhusanka 

I apologize for the delay. Related bug was fixed in [Bugfix train params](https://github.com/penny4860/Yolo-digit-detector/pull/18). Please checkout the latest [master](b6d0b03e59a9f68cf7aab72d6c86da64bfb86389) and check it out.

**Comment by penny4860** [comment]
@slimamk @TharakaMadhusanka 

The latest master commit ID has been changed to 8c5fcc88b62e6f7749af99116574f4a27dc8e48a.

**Comment by TharakaMadhusanka** [comment]
Sure !

**Comment by AliceDinh** [comment]
I still have that issue with newest master. I test [detection_example.ipynb](https://github.com/penny4860/Yolo-digit-detector/blob/master/detection_example.ipynb) using the [your pretrained model weight](https://drive.google.com/drive/folders/1Lg3eAPC39G9GwVTCH3XzF73Eok-N-dER)
![image](https://user-images.githubusercontent.com/20389638/51591355-56aaeb80-1f1f-11e9-8eca-fa04397cc261.png)

**Comment by penny4860** [comment]
@AliceDinh  My computer does not reproduce what you said. As in the ipython notebook, just two boxes are detected.

**Comment by janithwanni** [comment]
@AliceDinh I had the same issue when I tried to reproduce the results in Google Colab.
Was there any solution that was found? I found the same number of boxes as well 66 and 76. 
@penny4860 do we have to train the model from scratch to resolve the issue?

**Comment by janithwanni** [comment]
Might I add, getting the weights by training from scratch produced a set of weights that resolved the issue from 66 boxes and 76 boxes to 0 boxes and 1 box with a threshold of 0.3.
Reducing the threshold to 0.05 brought the results to 1 box and 2 boxes 😂 
I think something went wrong with training. let me check again.

**Comment by penny4860** [comment]
@janithwanni Thank you for using this project. In the case of Yolo v2, learning is a rather difficult problem. Yolo v3 has relieved much of this problem, so we recommend using [Yolo v3](https://github.com/penny4860/tf-eager-yolo3#2-svhn-dataset--httpufldlstanfordeduhousenumbers) at this point.
